name: 'Create .docx file'

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  pull-requests: read
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  make-docx:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: create file list
        id: files_list
        run: |
          mkdir output  # create output dir
          echo "files=$(printf '"%s" ' [0-9]*.md)" > $GITHUB_OUTPUT

      - name: Build .docx
        uses: docker://pandoc/latex:2.9
        with:
          args: --defaults=settings.yaml ${{ steps.files_list.outputs.files }}

      - name: Upload .docx
        uses: actions/upload-artifact@v3
        with:
          name: sample-document.docx
          path: sample-document.docx
